DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.15
  min_vel_x: -0.60

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  0.15
  min_vel_trans:  -0.60

  max_vel_theta: 40000
  min_vel_theta: -40000

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 15000

# Goal Tolerance Parametes
  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 4.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 50
  controller_frequency: 10.0

# Trajectory Scoring Parameters
  path_distance_bias: 40.0
  goal_distance_bias: 20.0
  occdist_scale: 0.03
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
